version: '3'

services:
  pgadmin4:
    image: "dpage/pgadmin4"
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.pgadmin4.loadbalancer.server.port=8085"
        - "traefik.http.routers.api.entrypoints=web"
        # - "traefik.http.services.pgadmin4.loadbalancer.server.port=80"
        # - "traefik.http.routers.pgadmin4-http.middlewares=pgadmin4-https@docker"
        - "traefik.docker.network=net-2"
        - "traefik.http.routers.pgadmin4-http.rule=Host(`pgadm.${OPEN_DNS_8085}`)"
        - "traefik.http.routers.pgadmin4.rule=Host(`pgadm.${OPEN_DNS_8085}`)"
        # - "traefik.http.routers.pgadmin4-http.entrypoints=web"
    environment:
      PGADMIN_DEFAULT_EMAIL: target@targetso.com
      PGADMIN_DEFAULT_PASSWORD: target
      PGADMIN_LISTEN_PORT: 8085

    # ports:
      # - "8085:80"
    networks:
      - net-2
      - net-3

networks:
  net-2:
    external: true
  net-3:
    external: true

