version: '3'

services:
  postgres:
    image: "postgres:alpine3.19"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: target
      POSTGRES_PASSWORD: target
    networks:
      - net-3
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=false"

volumes:
  pg-data:

networks:
  net-3:
    external: true
