version: '3'

services:
  postgres:
    image: "kartoza/postgis:12.0"
    ports:
      - 5446:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: target
      POSTGRES_PASSWORD: target
    networks:
      - net-3
    volumes:
      - 'pg-data:/var/lib/postgresql'
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=false"

  pgadmin4:
    image: "dpage/pgadmin4"
    volumes:
      - ./pgadmin_data:/pgadmin
    depends_on: 
      - postgres
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.pgadmin4.loadbalancer.server.port=8085"
        # - "traefik.http.services.pgadmin4.loadbalancer.server.port=80"
        - "traefik.http.routers.pgadmin4-http.middlewares=pgadmin4-https@docker"
        - "traefik.docker.network=net-2"
        - "traefik.http.routers.pgadmin4-http.rule=Host(`pgadm.ip172-18-0-45-cntlg0ol2o9000bak8q0-80.direct.labs.play-with-docker.com`)"
        - "traefik.http.routers.pgadmin4.rule=Host(`pgadm.ip172-18-0-45-cntlg0ol2o9000bak8q0-80.direct.labs.play-with-docker.com`)"
        - "traefik.http.routers.pgadmin4-http.entrypoints=web"
    environment:
      PGADMIN_DEFAULT_EMAIL: target@targetso.com
      PGADMIN_DEFAULT_PASSWORD: target
    ports:
      - "8085:80"
    networks:
      - net-2
      - net-3

volumes:
  pg-data:

networks:
  net-2:
    external: true
  net-3:
    external: true
