version: '3.7'

services:
  tomcat-demo:
    image: tomcat:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tomcat.rule=Host(`ip172-18-0-45-cntlg0ol2o9000bak8q0-80.direct.labs.play-with-docker.com`)"
        - "traefik.http.services.tomcat.loadbalancer.server.port=8080"
        - "traefik.docker.network=net-1"
        - "traefik.constraint-label=traefik-public"
    networks:
      - net-1

networks:
  net-1:
    external: true
